### ISSUE TITLE
Search/URL Bar not functioning as expected

### ISSUE THREAD

**Issue by degreeszero** [jessebofill/DeckWebBrowser#5] opened 2023-08-29 16:50 UTC
With the Browser open, if I navigate my cursor to the search bar at the top and enter a query, the deck searches my game library. It does not execute a search in the default search engine, nor does it allow for navigation to a URL. Essentially I have not been able to open any webpages except for the default homepage. Furthermore, I cannot edit the URL of the default Homepage in settings.

**Comment by jessebofill** [comment] 2023-08-29 19:31
when you say cursor, do you mean mouse cursor or navigation via d pad?

**Comment by degreeszero** [comment] 2023-08-29 22:39
Navigation via D-pad in gaming mode.On Aug 29, 2023, at 12:31, jbofill ***@***.***> wrote:﻿
when you say cursor, do you mean mouse cursor or navigation via d pad?

**Comment by jessebofill** [comment] 2023-08-29 23:38
What channel are you on for os/ steam client

**Comment by degreeszero** [comment] 2023-08-30 05:41
Stable.On Aug 29, 2023, at 16:39, jbofill ***@***.***> wrote:﻿
What channel are you on for os/ steam client

**Comment by jessebofill** [comment] 2023-08-30 23:05
I’ll need some more information and possibly have you do some testing in order to figure out why it’s not working for you, cus I can’t reproduce the issue. Do you happen to have discord? It would be easier to communicate in the dedicated support channel.

**Comment by degreeszero** [comment] 2023-08-31 18:52
Yes, my discord username is superflowOn Aug 30, 2023, at 16:06, jbofill ***@***.***> wrote:﻿
I’ll need some more information and possibly have you do some testing in order to figure out why it’s not working for you, cus I can’t reproduce the issue. Do you happen to have discord? It would be easier to communicate in the dedicated support channel.

**Comment by jessebofill** [comment] 2023-09-01 23:47
Please tag me @jeiza in the support channel https://discord.com/channels/960281551428522045/1136334937214165153 and I will ask you some more questions.

**Comment by BenDavidson90** [comment] 2023-09-05 09:18
Hi, same problem here since I installed it in july.
I never found how to enter an URL, when I go to the search bar, like @degreeszero it search on my library.
SteamOS stable 3.4.10, kernel 5.13.0-valve37-1-neptune

**Comment by jessebofill** [comment] 2023-09-06 20:36
> Hi, same problem here since I installed it in july. I never found how to enter an URL, when I go to the search bar, like @degreeszero it search on my library. SteamOS stable 3.4.10, kernel 5.13.0-valve37-1-neptune

I will do some more investigating to see if I can figure out why it wouldn't patch and may need to ask you some more questions.

**Comment by TomFaulkner** [comment] 2023-09-07 18:50
I came here to try to find a way around this issue as well. It worked briefly but now the search only searches the library. I'm on the SteamOS beta or nightly branch.

**Comment by jessebofill** [comment] 2023-09-07 21:36
Ok I have made some changes that hopefully fix this issue. I'm just waiting for it to get accepted to the Decky testing store. I will let you all know when it does, so you can test it out.

**Comment by jessebofill** [comment] 2023-09-09 15:46
Ok the update has skipped the testing store and gone straight to the main decky store. To anyone who has had this issue, please test out the new update (v1.0.1) and report back if it works for you or not. Thanks

**Comment by BenDavidson90** [comment] 2023-09-09 15:56
> Ok the update has skipped the testing store and gone straight to the main decky store. To anyone who has had this issue, please test out the new update (v1.0.1) and report back if it works for you or not. Thanks

Yes, it works ! Thanks ! 😄

**Comment by jessebofill** [comment] 2023-09-09 15:58
> > Ok the update has skipped the testing store and gone straight to the main decky store. To anyone who has had this issue, please test out the new update (v1.0.1) and report back if it works for you or not. Thanks
> 
> Yes, it works ! Thanks ! 😄

Awesome! great to hear!

**Comment by jessebofill** [comment] 2023-09-09 16:01
@degreeszero if it works for you too then i will close this issue.

**Comment by shataf-alriq** [comment] 2023-09-19 22:42
I also had this issue but the new update seems to have fixed for me (didn't work when I updated but worked when I reinstalled).. the search bar now works, however when I press the search button.. the search bar gets covered by the Use Touch.. 

![PXL_20230919_223736568_1](https://github.com/jessebofill/DeckWebBrowser/assets/145508211/81b255ab-e610-4c76-bb43-190a83e7247a)

**Comment by jessebofill** [comment] 2023-09-20 19:40
> I also had this issue but the new update seems to have fixed it for me (didn't work when I updated but worked when I reinstalled).. the URL search bar now works, however when I press the search button (magnifying icon on the right).. the search bar gets covered by the Use Touch when I type..
> 

I see what you mean. Unfortunately there's nothing I can really do about that. Modifying the search bar behavior is extremely finicky and difficult, and some things I just can't control. The problem is with keyboard when using touchscreen typing. All I can do is suggest not to use touchscreen to type (you can still type with touchscreen, it will just be hidden). If you start using touch pads, the text will be visible again.

**Closed** 2023-09-22 17:24 UTC
